# Generated by Django 3.0.3 on 2020-03-05 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='frist_name',
            new_name='first_name',
        ),
    ]
